PREFIX dct:   <http://purl.org/dc/terms/>
PREFIX faldo: <http://biohackathon.org/resource/faldo#>
PREFIX gvo:   <http://genome-variation.org/resource#>

SELECT ?reference ?start ?stop
WHERE {
  VALUES ?tgv_id { "{{tgv_id}}" }

  GRAPH <http://togovar.biosciencedbc.jp/variant> {
    {
      ?variant a gvo:SNV ;
        dct:identifier ?tgv_id ;
        faldo:location/faldo:reference ?reference ;
        faldo:location/faldo:position ?start .
    } UNION {
      ?variant a gvo:Insertion ;
        dct:identifier ?tgv_id ;
        faldo:location/faldo:reference ?reference ;
        faldo:location/faldo:before ?start .
    } UNION {
      ?variant a gvo:Deletion ;
        dct:identifier ?tgv_id ;
        faldo:location/faldo:begin/faldo:reference ?reference ;
        faldo:location/faldo:begin/faldo:before ?start ;
        faldo:location/faldo:end/faldo:after ?stop .
    } UNION {
      ?variant a gvo:Indel ;
        dct:identifier ?tgv_id ;
        faldo:location/faldo:begin/faldo:reference ?reference ;
        faldo:location/faldo:begin/faldo:before ?start ;
        faldo:location/faldo:end/faldo:after ?stop .
    } UNION {
      ?variant a gvo:MNV ;
        dct:identifier ?tgv_id ;
        faldo:location/faldo:reference ?reference ;
        faldo:location/faldo:begin ?start ;
        faldo:location/faldo:end ?stop .
    }
  }
}
