DEFINE sql:select-option "order"

PREFIX tgv:   <http://togovar.biosciencedbc.jp/variant/>

SELECT ?uri
FROM <http://togovar.biosciencedbc.jp/graph/variant>
WHERE {
  VALUES ?variant { tgv:{{tgv_id}} }

  ?variant rdfs:seeAlso ?uri
  FILTER REGEX(STR(?uri), "^{{prefix}}")
}
