DEFINE sql:select-option "order"

PREFIX tgv:   <http://togovar.biosciencedbc.jp/variant/>
PREFIX faldo: <http://biohackathon.org/resource/faldo#>
PREFIX hco:   <http://identifiers.org/hco/>

SELECT DISTINCT ?chromosome ?position
FROM <http://togovar.biosciencedbc.jp/graph/variant>
WHERE {
  VALUES ?variant { tgv:{{tgv_id}} }

  ?variant faldo:location/faldo:begin?/faldo:reference ?reference .
  ?variant faldo:location/faldo:begin?/faldo:position ?position .

  BIND( REPLACE(REPLACE(STR(?reference), hco:, ""), "#.*", "") AS ?chromosome )
}
