PREFIX faldo: <http://biohackathon.org/resource/faldo#>
PREFIX hco:   <http://identifiers.org/hco/>
PREFIX tgvv:  <http://togovar.biosciencedbc.jp/vocabulary/>

SELECT DISTINCT ?type ?chromosome ?start ?stop
FROM <http://togovar.biosciencedbc.jp/variation>
FROM <http://togovar.biosciencedbc.jp/ensembl37>
FROM <http://togovar.biosciencedbc.jp/hgnc>
WHERE {
 VALUES ?hgnc_uri { <http://identifiers.org/hgnc/{{ hgnc_id }}> }

  ?hgnc_uri rdfs:label ?symbol.

  ?ensg rdfs:label ?symbol.
  ?_cn tgvv:gene ?ensg.

  ?ensg a ?type ;
    faldo:location/faldo:begin?/faldo:reference ?reference ;
    faldo:location/faldo:begin?/faldo:position ?start ;
    faldo:location/faldo:end?/faldo:position ?stop .

  BIND(REPLACE(REPLACE(STR(?reference), hco:, ""), "#.*", "") AS ?chromosome).
}
