PREFIX dct: <http://purl.org/dc/terms/>
SELECT DISTINCT ?xref ?approved_name
FROM <http://togovar.biosciencedbc.jp/hgnc>
WHERE {
  VALUES ?hgnc_uri { <http://identifiers.org/hgnc/{{hgnc_id}}> }

  ?hgnc_uri rdfs:label ?xref;
    dct:description ?approved_name.
}
