DEFINE sql:select-option "order"

PREFIX dct:   <http://purl.org/dc/terms/>
PREFIX faldo: <http://biohackathon.org/resource/faldo#>
PREFIX hco:   <http://identifiers.org/hco/>

SELECT ?label
FROM <http://togovar.biosciencedbc.jp/variation>
WHERE {
  VALUES ?tgv_id { "{{tgv_id}}" }

  ?variation dct:identifier ?tgv_id ;
    rdfs:label ?label .
}
