DEFINE sql:select-option "order"

PREFIX tgv: <http://togovar.biosciencedbc.jp/variant/>

SELECT DISTINCT ?dbsnp
FROM <http://togovar.biosciencedbc.jp/graph/variant>
WHERE {
  VALUES ?variant { tgv:{{tgv_id}} }

  ?variant rdfs:seeAlso ?dbsnp .
  FILTER STRSTARTS(STR(?dbsnp), 'http://identifiers.org/dbsnp/')
}
